apiVersion: v1
kind: Namespace
metadata:
  name: keda
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-operator
  namespace: keda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keda-operator
  template:
    metadata:
      labels:
        app: keda-operator
    spec:
      containers:
      - name: keda-operator
        image: kedacore/keda:latest
        command: ["/keda"]
        args: ["operator"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-metrics-apiserver
  namespace: keda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keda-metrics-apiserver
  template:
    metadata:
      labels:
        app: keda-metrics-apiserver
    spec:
      containers:
      - name: keda-metrics-apiserver
        image: kedacore/keda-metrics-apiserver:latest